# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      id: dotnet-cache
      with:
        key: ${{ runner.os }}-dotnet-maui-desktop-workload-${{ hashFiles('./global.json') }}
        path: |
          ${{ github.workspace }}/.dotnet/packs
          ${{ github.workspace }}/.dotnet/sdk-manifests
          ${{ github.workspace }}/.dotnet/library-packs
          ${{ github.workspace }}/.dotnet/metadata
          
        restore-keys: |
          ${{ runner.os }}-dotnet-maui-desktop-workload-${{ hashFiles('./global.json') }}

    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: './global.json'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - run: dotnet workload install maui-desktop
      if: steps.dotnet-cache.outputs.cache-hit != 'true'
    
    - run: dotnet workload restore ./github-actions-maui-app.sln
      if: steps.dotnet-cache.outputs.cache-hit == 'true'

    - run: dotnet restore --locked-mode
      
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
