# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build MAUI Desktop App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: './global.json'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Setup .NET MAUI
      uses: ./.github/actions/setup-maui
      with:
        SOLUTION: './github-actions-maui-app.sln'
        GLOBAL_JSON: './global.json'

    - run: dotnet restore --locked-mode
      
    - name: Publish application 
      run: dotnet publish .\Maui.App\ -f net8.0-windows10.0.19041.0 -c Release -bl -o ./app_bin --no-restore
    
    - name: Upload App as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-app--${{ github.head_ref }}--${{ github.sha }}
        path: ./app_bin
        if-no-files-found: error
        retention-days: 1
        overwrite: true

  test-ui:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: './global.json'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Download App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ runner.os }}-app--${{ github.head_ref }}--${{ github.sha }}

    - name: Run UI Tests
      run: |
        echo "Running UI Tests"
        echo "App Path: ${{ github.workspace }}/app_bin"