# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: './global.json'
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: "List cache directory"
      run: |
        if (Test-Path -Path ${{ env.NUGET_PACKAGES }}) {
          ls ${{ env.NUGET_PACKAGES }}
        } else {
          echo "Directory '${{ env.NUGET_PACKAGES }}' does not exist"
        }    
      shell: pwsh

    - run: dotnet workload install maui
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: "List cache directory"
      run: |
        if (Test-Path -Path ${{ env.NUGET_PACKAGES }}) {
          ls ${{ env.NUGET_PACKAGES }}
        } else {
          echo "Directory '${{ env.NUGET_PACKAGES }}' does not exist"
        }    
      shell: pwsh
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
