# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - run: ls ${{ env.NUGET_PACKAGES }}

    - name: Restore workload dependencies
      run: dotnet workload restore --locked-mode
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - run: ls ${{ env.NUGET_PACKAGES }}
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
