name: Code format verification

on:
  workflow_call: 
    outputs:
      success:
        description: 'Result of verification'
        value: ${{ jobs.verify.result == 'success' }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: './global.json'
    - run: dotnet tool restore
    - run: dotnet csharpier --check .
    - run: dotnet format --verify-no-changes --no-restore # Should cache and restore nugets for 3.party analysers